---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Build resources for anarchy
  name: anarchy-build

parameters:
- name: GIT_REPO
  value: https://github.com/redhat-gpte-devopsautomation/agnosticv-operator.git
- name: NAME
  value: agnosticv-operator

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: true
        from:
          kind: DockerImage
          name: ${KOPF_S2I_IMAGE}
    triggers: []
