---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: agnosticv-repo deploy
  name: agnosticv-repo-deploy

parameters:
- name: AGNOSTICV_REPO_NAME
  value: agnosticv-repo
- name: AGNOSTICV_SCM_URL
  required: true
- name: AGNOSTICV_SCM_REF
  value: master
- name: AGNOSTICV_SCM_SSH_KEY_SECRET
  value: agnosticv-repo-sshkey
- name: BABYLON_ANARCHY_GOVERNOR_REPO
  description: Git repository for Ansible role containing Babylon AnarchyGovernor logic
  value: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
- name: BABYLON_ANARCHY_GOVERNOR_VERSION
  description: Git reference for babylon governor repository
  value: master

objects:
- apiVersion: gpte.redhat.com/v1
  kind: AgnosticVRepo
  metadata:
    name: ${AGNOSTICV_REPO_NAME}
  spec:
    url: ${AGNOSTICV_SCM_URL}
    ref: ${AGNOSTICV_SCM_REF}
    sshKey: ${AGNOSTICV_SCM_SSH_KEY_SECRET}
    babylonAnarchyGovernorRepo: ${BABYLON_ANARCHY_GOVERNOR_REPO}
    babylonAnarchyGovernorVersion: ${BABYLON_ANARCHY_GOVERNOR_VERSION}
