---
# defaults file for agnosticv

default_description: |-
  Missing description, please define catalog_description in agnosticv
default_message: |-
  Missing message, please define catalog_message in agnosticv

default_labels:
  generated_by: agnosticv

repo_path: /opt/ansible/agnosticv/{{ url | b64encode }}
context_dir: ''
output_dir: /tmp/output_dir

# Ansible collections to install with AnsibleGalaxy
babylon_anarchy_collections:
- name: awx.awx
  version: 15.0.1

# Ansible roles to install with AnsibleGalaxy and order in which to execute
babylon_anarchy_roles:
- name: babylon_anarchy_governor
  src: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
  version: main

# AgnosticV CLI
agnosticv_client_path: /opt/ansible/agnosticv_cli

# default namespaces
governor_namespace: anarchy-operator
poolboy_namespace: poolboy

# Resource provider
resource_provider_default_lifespan:
  default: 3d
  maximum: 14d
  relativeMaximum: 5d
resource_provider_action_schedule:
  default_runtime: 4h
  maximum_runtime: 8h
