---
# defaults file for agnosticv

default_description: |-
  Missing description, please define __meta__.catalog.description in agnosticv
  or add a description.adoc file.
default_message: |-
  Missing message, please define in AgnosticV.

default_labels:
  generated_by: agnosticv

# take the first chars of checksum(url + ref) for uniq agnosticv name
repo_uniq_name: >-
  {{ ( ( url|default('') + ref|default('') ) | checksum)[:10] }}


repo_path: /opt/ansible/agnosticv/{{ repo_uniq_name }}
context_dir: ''

# Process only catalog items that changed in git
# Set this to false if you want to process all catalog items
# all the time.
process_changes_only: true

output_dir: /tmp/output_dir

# Ansible collections to install with AnsibleGalaxy
babylon_anarchy_collections:
- name: awx.awx
  version: 15.0.1

# Ansible roles to install with AnsibleGalaxy and order in which to execute
babylon_anarchy_roles:
- name: babylon_anarchy_governor
  src: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
  version: main

# agnosticv dir can be inside the repository
agnosticv_path: >-
  {%- if context_dir is defined and context_dir is not none -%}
  {{ (repo_path, context_dir) | join('/') }}
  {%- else -%}
  {{ repo_path }}
  {%- endif -%}

# AgnosticV CLI
agnosticv_client_path: /opt/ansible/agnosticv_cli

default_category: Other

# default namespaces
default_anarchy_namespace: >-
  {{ lookup('env','ANARCHY_NAMESPACE')
  | default('anarchy-operator', true) }}

default_catalog_namespace: >-
  {{ lookup('env','CATALOG_NAMESPACE')
  | default('babylon-catalog', true) }}

poolboy_namespace: >-
  {{ lookup('env','POOLBOY_NAMESPACE')
  | default('poolboy', true) }}

# Resource provider
resource_provider_default_lifespan:
  default: 3d
  maximum: 14d
  relativeMaximum: 5d
resource_provider_runtime_default: 4h
resource_provider_runtime_maximum: 8h

anarchy_governor_standard_actions:
- provision
- destroy
- start
- stop
- status

error_log_file: /tmp/{{ repo_uniq_name }}_errors.txt
retry_log_file: /tmp/{{ repo_uniq_name }}_retry.txt


# Logstash reports
logstash_report: false
logstash_protocol: https
# logstash_hostname: ...
# logstash_port: ...
# logstash_user: ...
# logstash_password: ...
# logstash_from: ...
