---
# defaults file for agnosticv

default_description: |-
  Missing description, please define catalog_description in agnosticv
default_message: |-
  Missing message, please define catalog_message in agnosticv

default_labels:
  generated_by: agnosticv

repo_path: /opt/ansible/agnosticv
output_dir: /tmp/output_dir

babylon_anarchy_governor_repo: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
babylon_anarchy_governor_version: master
