apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agnosticv.name" . }}
  namespace: {{ include "agnosticv.namespaceName" . }}
  labels:
    {{- include "agnosticv.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agnosticv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agnosticv.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "agnosticv.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ansible
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "{{ include "agnosticv.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          resources:
            {{- toYaml .Values.resources.ansible | nindent 12 }}
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "agnosticv.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ include "agnosticv.name" . }}
          - name: ANARCHY_NAMESPACE
            value: {{ .Values.anarchy.namespace }}
          resources:
            {{- toYaml .Values.resources.ansible | nindent 12 }}
      serviceAccountName: {{ include "agnosticv.name" . }}
      volumes:
        - name: runner
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
