apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agnosticvrepos.gpte.redhat.com
spec:
  group: gpte.redhat.com
  names:
    kind: AgnosticVRepo
    listKind: AgnosticVRepoList
    plural: agnosticvrepos
    singular: agnosticvrepo
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
