apiVersion: gpte.redhat.com/v1
kind: AgnosticVRepo
metadata:
  name: gpte-agnosticv
spec:
  url: git@github.com:rhpds/agnosticv.git
  ref: master
  sshKey: agnosticv-operator-sshkey
  contextDir: ''
  babylon_anarchy_roles:
  - name: babylon_anarchy_governor
    src: https://github.com/rhpds/babylon_anarchy_governor.git
    version: main

