apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: agnosticv-operator
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - namespaces/status
    verbs:
    - list
    - get
    - watch
    - create
    - patch
  - apiGroups:
    - ""
    - template.openshift.io
    resources:
    - templates
    verbs:
      - '*'

  - apiGroups:
    - ""
    - anarchy.gpte.redhat.com
    resources:
    - anarchygovernors
    verbs:
      - '*'
