---
- block:
    - debug:
        msg: |
          {{ agnosticv_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

    - include_tasks: include_vars.yml
    - include_tasks: generate_catalog_item_tasks.yml

  rescue:
    - debug:
        msg: |
          FAIL {{ agnosticv_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

    - name: Set flag_fail to true
      set_fact:
        flag_fail: true
