---
- block:
    - debug:
        msg: |
          {{ agnosticv_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

    - include_tasks: include_vars.yml
    - include_tasks: generate_catalog_item_tasks.yml

  rescue:
    - debug:
        msg: |
          FAIL {{ agnosticv_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

    - name: Add line to text to be sent to google chat room
      lineinfile:
        path: "{{ google_chat_text_file }}"
        line: FAIL {{ url }} > {{ account }} > {{ catalog_item }} > {{ stage }}
