---
- include_tasks: specified_behaviors.yml

- set_fact:
    catalog_item_name: "{{ account | replace('_', '-') }}.{{ catalog_item | lower | regex_replace('_', '-') }}.{{ stage }}"

- name: Use namespace defined in the catalog item YAML
  set_fact:
    anarchy_namespace: >-
      {{ merged_vars.__meta__.anarchy.namespace | default(default_anarchy_namespace) }}
    catalog_item_namespace: >-
      {{ merged_vars.__meta__.catalog.namespace | default('openshift') }}

- name: Get k8s fact for the catalog item
  k8s_info:
    api_version: babylon.gpte.redhat.com/v1
    kind: catalogitems
    name: "{{ catalog_item_name }}"
    namespace: "{{ catalog_item_namespace }}"
  register: catalogitems_facts

- name: Get k8s fact for the template
  k8s_info:
    api_version: template.openshift.io/v1
    kind: templates
    name: "{{ catalog_item_name }}"
    namespace: "{{ catalog_item_namespace }}"
  register: template_facts

- name: Get k8s fact for the Governor
  k8s_info:
    api_version: anarchy.gpte.redhat.com/v1
    kind: AnarchyGovernor
    name: "{{ catalog_item_name }}"
    namespace: "{{ anarchy_namespace }}"
  register: governor_facts


- name: Get k8s fact for the ResourceProvider
  k8s_info:
    api_version: poolboy.gpte.redhat.com/v1
    kind: ResourceProvider
    name: "{{ catalog_item_name }}"
    namespace: "{{ poolboy_namespace }}"
  register: resource_provider_facts

- name: Create Namespace
  k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  loop:
    - "{{ anarchy_namespace }}"
    - "{{ catalog_item_namespace }}"

- name: Create / Update OpenShift template object
  k8s:
    state: present
    definition: "{{ lookup('template', 'template.yml.j2' ) | from_yaml }}"
    force: true
  vars:
    _name: "{{ catalog_item_name }}"
    _namespace: "{{ catalog_item_namespace }}"
    # Use description.adoc first, then variables
    _description: >-
      {{ lookup('file',
                ( agnosticv_path,
                  c_i | dirname,
                  'description.adoc') | join('/'),
                  errors='ignore')
      | default(merged_vars.__meta__.catalog.description, true)
      | default(default_description)
      }}
    current_resource_version: >-
      {{ template_facts.resources[0].metadata.resourceVersion
      if template_facts.resources else '' }}

- name: Create / Update Babylon Catalog Item object
  k8s:
    state: present
    definition: "{{ lookup('template', 'catalog_item.yml.j2') | from_yaml }}"
    force: true
  vars:
    _catalog: "{{ merged_vars.__meta__.catalog }}"
    _namespace: "{{ catalog_item_namespace }}"
    _name: "{{ catalog_item_name }}"
    # Use description.adoc first, then variables
    _description: >-
      {{ lookup('file',
                ( agnosticv_path,
                  c_i | dirname,
                  'description.adoc') | join('/'),
                  errors='ignore')
      | default(merged_vars.__meta__.catalog.description, true)
      | default(default_description)
      }}
    current_resource_version: >-
      {{ catalogitems_facts.resources[0].metadata.resourceVersion
      if catalogitems_facts.resources else '' }}

- name: Create / Update OpenShift Governor object
  k8s:
    state: present
    definition: "{{ lookup('template', 'governor.yml.j2') | from_yaml }}"
    force: true
  vars:
    _name: "{{ catalog_item_name }}"
    _namespace: "{{ anarchy_namespace }}"
    current_resource_version: >-
      {{ governor_facts.resources[0].metadata.resourceVersion
      if governor_facts.resources else '' }}

- name: Create / Update Poolboy ResourceProvider
  k8s:
    state: present
    definition: "{{ lookup('template', 'resource_provider.yml.j2') | from_yaml }}"
    force: true
  vars:
    _name: "{{ catalog_item_name }}"
    _namespace: "{{ poolboy_namespace }}"
    _governor: "{{ catalog_item_name }}"
    _catalog: "{{ merged_vars.__meta__.catalog }}"
    current_resource_version: >-
      {{ resource_provider_facts.resources[0].metadata.resourceVersion
      if resource_provider_facts.resources else '' }}
