---
- debug:
    msg: |
      {{ repo_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

- include_tasks: include_vars.yml

- include_tasks: specified_behaviors.yml

# If the catalog item defines some __meta__ then it's a candidate
- when:
  - "'__meta__' in merged_vars"
  - "'catalog' in merged_vars.__meta__"
  block:
    - name: Create output_dir directory
      file:
        state: directory
        path: "{{ output_dir }}"

    - set_fact:
        catalog_item_name: "{{ account | replace('_', '-') }}.{{ catalog_item | lower | regex_replace('_', '-') }}.{{ stage }}"

    - name: Get the namespace for Governor objects from environment variables
      set_fact:
        governor_namespace: "{{ lookup('env','ANARCHY_NAMESPACE') }}"

    - name: Use the default namespace anarchy-operator for Governors objects
      set_fact:
        governor_namespace: anarchy-operator
      when: governor_namespace == ''

    - name: Use namespace defined in the catalog item YAML
      set_fact:
        template_namespace: >-
          {{ merged_vars.__meta__.catalog.namespace | default('openshift') }}

    - name: Get k8s fact for the template
      k8s_facts:
        api_version: template.openshift.io/v1
        kind: templates
        name: "{{ catalog_item_name }}"
        namespace: "{{ template_namespace }}"
      register: template_facts

    - name: Generate Catalog item
      template:
        src: catalog_item.yml.j2
        dest: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}.yml"
      vars:
        _name: "{{ catalog_item_name }}"
        current_resource_version: >-
          {{ template_facts.resources[0].metadata.resourceVersion if template_facts.resources else '' }}

    - name: Get k8s fact for the Governor
      k8s_facts:
        api_version: anarchy.gpte.redhat.com/v1
        kind: AnarchyGovernor
        name: "{{ catalog_item_name }}"
        namespace: "{{ governor_namespace }}"
      register: governor_facts

    - name: Generate Catalog item governor
      template:
        src: governor.yaml.j2
        dest: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}_governor.yml"
      vars:
        _name: "{{ catalog_item_name }}"
        current_resource_version: >-
          {{ governor_facts.resources[0].metadata.resourceVersion if governor_facts.resources else '' }}

    - name: Create Namespace
      k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
      loop:
        - "{{ governor_namespace }}"
        - "{{ template_namespace }}"

    - name: Create / Update OpenShift template object
      k8s:
        state: present
        src: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}.yml"
        namespace: "{{ template_namespace }}"
        force: yes

    - name: Create / Update OpenShift Governor object
      k8s:
        state: present
        src: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}_governor.yml"
        force: yes
        namespace: "{{ governor_namespace }}"
