---
- block:
    - debug:
        msg: |
          {{ agnosticv_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

    - include_tasks: include_vars.yml
    - include_tasks: generate_catalog_item_tasks.yml

  rescue:
    - debug:
        msg: |
          FAIL {{ agnosticv_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

    - when: google_chat_webhook_url is defined
      uri:
        url: "{{ google_chat_webhook_url }}"
        method: POST
        status_code: 200
        body_format: json
        body:
          text: |-
            FAIL {{ url }} > {{ account }} > {{ catalog_item }} > {{ stage }}
