---
- name: Run AgnosticV client
  command: >-
    {{ agnosticv_client_path }} --merge {{ c_i }}
  args:
    chdir: "{{ agnosticv_path }}"
  register:
    r_agnosticv_client_merge

- name: Set merged_vars
  set_fact:
    merged_vars: "{{ r_agnosticv_client_merge.stdout | from_yaml }}"

- debug:
    var: merged_vars
    verbosity: 3
