---
- name: Get Google Chat WebHook k8s secret
  k8s_facts:
    api_version: v1
    kind: Secret
    name: "{{ google_chat_webhook_secret }}"
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
  register: r_google_chat_webhook
  no_log: true

- name: Save google webhook URL as var
  set_fact:
    google_chat_webhook_url: >-
      {{ r_google_chat_webhook.resources[0].data.url | b64decode }}
  no_log: true
