---
# - name: Print some debug information
#   vars:
#     msg: |
#         Module Variables ("vars"):
#         --------------------------------
#         {{ vars | to_nice_json }}

#         HOST Variables ("hostvars"):
#         --------------------------------
#         {{ hostvars | to_nice_json }}
#   debug:
#     msg: "{{ msg.split('\n') }}"
#   tags: debug_info

- when: ssh_key is defined
  block:
    - name: Get SSH secret key
      k8s_facts:
        api_version: v1
        kind: Secret
        name: "{{ ssh_key }}"
        namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
      register: ssh_key_r
      no_log: true

    - file:
        path: /opt/ansible/.ssh
        state: directory
        mode: 0700

    - name: Import SSH deploy key to pull the repo
      copy:
        dest: /opt/ansible/.ssh/id_rsa
        mode: 0600
        content: "{{ ssh_key_r.resources[0].data.id_rsa | b64decode }}"
      no_log: true

    - name: Clone agnosticv repo
      git:
        accept_hostkey: true
        repo: "{{ url }}"
        version: "{{ ref }}"
        dest: "{{ repo_path }}"
        key_file: /opt/ansible/.ssh/id_rsa

- when: ssh_key is not defined
  name: Clone agnosticv repo
  git:
    accept_hostkey: true
    repo: "{{ url }}"
    version: "{{ ref }}"
    dest: "{{ repo_path }}"


- name: Find all catalog items
  find:
    recurse: yes
    use_regex: yes
    paths:
      - "{{ repo_path }}"
    excludes:
      - ^common
      - ^account
      - '\\.git'
    patterns:
      - '.*ya?ml$'
  register: r_catalogitems


- loop: "{{ r_catalogitems.files }}"
  loop_control:
    loop_var: c_i
    label: c_i.path
  include_tasks: generate_catalog_item.yml
  when: account != 'EXAMPLE_ACCOUNT'
  vars:
    account: "{{ c_i.path.split('/')[-3] }}"
    catalog_item: "{{ c_i.path.split('/')[-2] }}"
    stage: "{{ c_i.path.split('/')[-1] | regex_replace('\\.ya?ml$', '') }}"
