---
# GPTE Reporting
# Detect if reporting is needed for that catalog item.
- name: GPTE Reporting is enabled
  when: >-
    'gpte_db' in merged_vars.__meta__.secrets
    | default([])
    | selectattr('var', 'defined')
    | list
    | json_query('[].var')

  set_fact:
    gpte_reporting: true

# RHPDS virtualenvs -> EE  automatic creation
- name: Override EE with default_execution_environment if not defined
  when: >-
    ansible_control_plane == 'controller'
    and execution_environment | default('', true) == ''
    and default_execution_environment | default('', true) != ''
  vars:
    to_merge:
      __meta__:
        deployer:
          execution_environment: "{{ default_execution_environment }}"

  set_fact:
    merged_vars: "{{ merged_vars | combine(to_merge) }}"
